FORMAT: 1A
HOST: https://jp-api4-stage.boku.com

# Boku Direct Payments API
## API Security

Security is a significant consideration for payment platforms. As part of the registration process for each registered merchant account, merchants receive a security key used to authenticate communications in either direction.

Developers should consult the [Boku API Signature Authentication Guide](page:guides/api-signature-authentication-guide) for additional details with respect to implementing security on the Boku APIs.

## API Usage

When a consumer chooses to use a local payment-method (wallet), the consumer must go through an 'optin' flow to authenticate. This is accomplished using a redirect to the issuer's app or website where the consumer authenticates and completes the opt-in process.

After the consumer adds their local payment-method (wallet), as their registered payment method, the 'charge' method is used to charge the consumer's local payment-method.

If a customer decides to refund a transaction, the 'refund-charge' method can be used to refund the transaction.

## API Versioning

The Boku Payment Gateway API is versioned to provide support for changes to functionality without affecting existing integrations.  Each API URL includes version information that enables distinct functionality across different versions.

There are several types of changes that could result in a new API version:

1. New API functionality – new APIs, new parameters, additional information in responses, improved error reporting.
2. Deprecated API functionality – deprecated APIs, deprecated parameters, deprecated error messages.
3. Changes in functionality – existing functional behavior changes such as the returned result of a call. A warning is changed to an error.  Validation becomes stricter or more lenient.

In these cases, Boku will release a new API version through a new endpoint(s). When new versions of existing APIs are added, support for existing versions is maintained.  Unless otherwise stated, as a rule, compatibility is maintained across versions.  Prior supported endpoints should have unchanged behavior. If an API is deprecated and scheduled to be removed, a notice of not less than 6 months will be given.  Requests for extensions to this period can be considered.

Boku may make changes to the API within an existing version without changing the version number. An example of a non-versioning change would be the addition of an optional field to a request or to a response.

## API Calls

### URL Scheme

All the below API calls are against URLs that follow the pattern,

``
https://${api-node}.boku.com/${api-family}/${api-version}/${api-call}
``

Definitions for the above placeholders:

* **api-node**: This follows the pattern '${country}-api4' (e.g. 'us-api4').
    * 'country' is the two letter country code of the end-user's payment-method against which the call is made.
    * The country code is required and is used for more efficient routing of the request.
    * The country code in the url must match the country code supplied in the `optin-request`.`country` element.
* **api-family**: Groups a family of related API methods.
    * In this API, family is either one of:
        * 'optin' - For interacting with the user or handset to obtain billing approval.
        * 'billing' - For actually performing billing operations against the user.
* **api-version**: In this version of the API, this value is always the string '3.0'.
    * Calls under different version numbers may be used in the future to introduce non-compatible API changes.
* **api-call**: The name particular API call or method to invoke, for example 'charge' or 'refund-charge'.
    * This usually matches the XML root element name, sans the '-request' suffix.

Fully qualified API call URLs are documented with each of the example calls detailed below.

# Group Charge

The 'charge' method submit charges to the associated consumer account that is registered with the merchant. The 'query-charge' method can be used in cases when the result of a prior charge is unknown. The 'reverse-charge' method can be used in cases when the result of a prior charge is unknown.

#### Charge (synchronous)

| Step | Description | API |
|------|-------------|-----|
| 1 | Merchant sends request to Boku to charge the consumer for a purchase using their registered payment method | 'charge' API method |
| 2 | Boku responds with success or failure | |

#### Charge (asynchronous)

| Step | Description | API |
|------|-------------|-----|
| 1 | Merchant sends the request to Boku to cancel a previously collected opt-in. Remove a payment method. | 'charge' API method |
| 2 | Boku responds with pending transaction status | |
| 3 | Merchant repeatedly polls until the purchase completes | |
| 4| Boku responds with success or failure | |

#### Reverse Charge

| Step | Description | API |
|------|-------------|-----|
| 1 | Merchant sends request to Boku to reverse a charge. Typically used when a merchant does not receive a response for a charge request | 'reverse-charge' API method |
| 2 | Boku responds with success or failure | |

#### Handling charge timeouts and network errors

In situations where the outcome of a `charge` call is uncertain to the merchant, the merchant must take action to resolve the final state of the charge.

These situations include timeouts where a well-formed in-progress response was sent to the merchant (reason code 23), a well-formed internal error response (reason code 35), a malformed response or unexpected HTTP error, as well as network errors such as connection-reset or socket-timeout where Boku may not have even received the original request at all.

The API provides several different ways to do this depending on how the merchant wishes to proceed with the charge:

  1. Give up and reverse the charge, regardless of whether it succeeded, failed, or is still in progress.
      * Issue a reverse-charge-request with the same merchant-request-id as was used for the charge-request.
  2. Continue to try and proceed with the charge, even if Boku never received the original request.
      * Send another charge-request identical to the first charge request. (Charge API is idempotent.)
  3. Check on the status of the charge, but do not start a new one if it is not processing already.
      * Poll the current status of the charge by sending a query-charge-request with the merchant-request-id used in the original charge-request.

### API idempotency and duplicate or retried requests

All API calls that can modify state or have side-effects are idempotent based on the `merchant-request-id` field during the idempotency window, which is 24 hours.

This means that any request received by Boku that has the same `merchant-request-id` to a prior request and has the same field values as that prior request, will either return a logically equivalent response to the previous response or in cases where the previous response was incomplete or indeterminate may return the current known state of the requested operation.

This feature exists to ensure accidental duplicate actions are not executed and to provide a general solution for retries in case of indeterminate outcomes.

It does ultimately rely on an appropriate merchant-request-id generation strategy to be useful, though, so merchants need to take great care in how they generate and supply those IDs.

#### Idempotency examples

Here are some examples using charge calls to illustrate this behavior:

* A charge request results in success, and then a duplicate charge request is received:
    * The second request receives the same success response as the first, and no new transaction is created.
* A charge request results in a billing error, such as insufficient funds, and then a duplicate charge request is received:
    * The second request receives the same error response as the first, and no new transaction is created.
* A charge request takes longer than the given `timeout` parameter and returns in-progress status (23), and then a duplicate charge request is received:
    * If the charge is still incomplete, will return the same in-progress status as last time.
    * If the charge has completed since the first response was returned, will return the final status of the charge (success or fail). This final status response will be identical to if the charge had completed within the timeout in the first place.
* A charge request resulted in an internal error and the processing state was indeterminate, so internal-error status (35) was returned, and then a duplicate charge request is received:
    * If the internal error occurred before the charge was recorded, no processing has occurred and so a new charge will be initiated by the second request.
    * If the internal error occurred after the charge was recorded, then the current status of the charge initiated in the first request will be returned.
    * If an internal error is experienced again, internal-error (35) will be returned.

#### On the idempotency window

The idempotency window is 24 hours, which means idempotency only applies for 24 hours after the last request was received with a given `merchant-request-id`.

If a request is re-issued for the first time over 24 hours after the original request was received it will be treated as a brand new request, and be entirely independent of the first request.

The 24-hour window is a sliding window based on the last usage of a particular `merchant-request-id`. Thus, for potentially long-running operations, requests may be repeatedly reissued for as long as necessary, as long as the gap between two requests never exceeds 24 hours.

#### On request conflicts

Idempotency applies only for duplicate requests on the basis of `merchant-request-id` that are logically equivalent. If a request is received with the same `merchant-request-id` and is not equivalent to the previous request then it will be rejected with error 124 "Idempotent request ID conflict".

Examples of conflicting are things such as using the same request ID for a request of a different type or issuing a duplicate charge request with a differing amount or user account.


## Billing 30 Charge [/billing/3.0/charge]

### charge [POST]
The 'charge' request processes a payment against a previously authorized opt-in. The 'optin-id' received in the 'optin'/'confirm-optin' response must be supplied in order to validate the consumer payment method.

If the 'optin-id' and the other parameters of the request are valid, the charge is submitted to the issuer for processing. A 'charge-id' is returned in the API response.

'Charge' may operate as a synchronous request, fully asynchronous, or synchronous with fallback to asynchronous after a timeout. The timeout is supplied with the request, or can default to a value configurable for the merchant. The 'charge' method returns a unique 'charge-id' in all cases where the request has been accepted for processing, including success, failure, and pending cases.

The 'charge' method is idempotent. If the same request is sent again (with the same 'merchant-request-id'), Boku will return the current status of the transaction. For example:

* If the transaction has completed successfully, a response code of "0" will be returned.
* If the transaction has completed with a billing error, a response code of "107" will be   returned

+ Request (<<Add Header Value>>)

    + Attributes (ChargeRequest)


    + Body

            <charge-request>
              <currency>USD</currency>
              <merchant-data>TY235g897qWs</merchant-data>
              <merchant-id>gatewaymerchant</merchant-id>
              <merchant-item-description>Puzzle game</merchant-item-description>
              <merchant-request-id>1002008</merchant-request-id>
              <merchant-transaction-id>9002005</merchant-transaction-id>
              <optin-id>IVXecDoa2f6Y3oOqp1f7</optin-id>
              <total-amount>5</total-amount>
              <timeout after="10000" />
              <consumer-ip-address>24.196.237.108</consumer-ip-address>
            </charge-request>


+ Response 200 (application/xml)
    + Attributes (ChargeResponse)


    + Body

            <charge-response>
              <result>
                <reason-code>0</reason-code>
                <message>Operation Successful</message>
                <retriable>false</retriable>
                <status>OK</status>
              </result>
              <timestamp>2015-02-40 04:44:16</timestamp>
              <charge-id>b368363a00bbddbf794eba33</charge-id>
              <charge-status>success</charge-status>
              <merchant-data>TY235g897qWs</merchant-data>
              <merchant-id>gatewaymerchant</merchant-id>
              <merchant-request-id>1002008</merchant-request-id>
              <merchant-transaction-id>9002005</merchant-transaction-id>
              <optin-id>IVXecDoa2f6Y3oOqp1f7</optin-id>
              <country>DE</country>
              <network-id>de-super</network-id>
            </charge-response>



## Billing 30 Query Charge [/billing/3.0/query-charge]

### queryCharge [POST]
Retrieves the status and all details of prior charges matching the given request criteria.

Each returned charge element is similar to a charge-response: although some elements are missing, all present elements have the same names, format and meaning as those in the original charge-response.

The query-charge API call is guaranteed to return transactions up to 1 year old. If the transaction was created before that period, this API may return no results.

Criteria are evaluated in an AND fashion, i.e. if more than one field is supplied then all will be used to filter the returned charge elements. In normal usage this is not relevant, since you would only supply one of the three fields by itself.

+ Request (<<Add Header Value>>)

    + Attributes (QueryChargeRequest)


    + Body

            <query-charge-request>
              <merchant-id>gatewaymerchant</merchant-id>
              <country>US</country>
              <merchant-transaction-id>9002005</merchant-transaction-id>
            </query-charge-request>


+ Response 200 (application/xml)
    + Attributes (QueryChargeResponse)


    + Body

            <query-charge-response>
              <result>
                <reason-code>0</reason-code>
                <message>Found 1 result(s)</message>
                <retriable>false</retriable>
                <status>OK</status>
              </result>
              <charges>
                <charges>
                  <result>
                    <reason-code>0</reason-code>
                    <message>Operation successful</message>
                    <retriable>false</retriable>
                    <status>OK</status>
                  </result>
                  <charge-status>success</charge-status>
                  <charge-id>b368363a00bbddbf794eba33</charge-id>
                  <timestamp>2015-02-40 04:44:16</timestamp>
                  <merchant-id>gatewaymerchant</merchant-id>
                  <merchant-transaction-id>9002005</merchant-transaction-id>
                  <country>DE</country>
                  <network-id>de-super</network-id>
                  <currency>USD</currency>
                  <total-amount>5</total-amount>
                  <merchant-item-description>Puzzle game</merchant-item-description>
                </charges>
              </charges>
            </query-charge-response>



## Billing 30 Reverse Charge [/billing/3.0/reverse-charge]

### reverseCharge [POST]
Reverses a charge request. This method is typically used when the result of a prior charge request is unknown. This can occur for a number of reasons, including:

* Network issue
* Request timed out by merchant
* Response received but could not be recorded

* A reversal will be accepted and a status of "OK" returned in almost all cases, regardless   of whether Boku actually received the original charge.

Aside from general request validation errors, a reversal will only be rejected if the original charge request was issued over 1 hour previously. After the 1 hour time period has expired, reversals are no longer allowed - please refund the transaction if required.

+ Request (<<Add Header Value>>)

    + Attributes (ReverseChargeRequest)


    + Body

            <reverse-charge-request>
              <merchant-id>gatewaymerchant</merchant-id>
              <merchant-request-id>1002008</merchant-request-id>
              <country>US</country>
            </reverse-charge-request>


+ Response 200 (application/xml)
    + Attributes (ReverseChargeResponse)


    + Body

            <reverse-charge-response>
              <result>
                <reason-code>0</reason-code>
                <message>Operation Successful</message>
                <retriable>false</retriable>
                <status>OK</status>
              </result>
              <timestamp>2015-02-40 04:44:16</timestamp>
              <merchant-id>gatewaymerchant</merchant-id>
              <merchant-request-id>1002008</merchant-request-id>
              <reversal-id>tRtbIVXyXVIbtRtytRt</reversal-id>
              <country>DE</country>
            </reverse-charge-response>



## Billing 30 Begin Single Charge [/billing/3.0/begin-single-charge]

### beginSingleCharge [POST]
The purpose of the 'begin-single-charge' API call is to initiate a one time charge. The 'begin-single-charge' call initiates a process in which a consumer is required to authenticate themselves each time a purchase is requested. This API provides a payment option for consumers who choose not to save a payment method with the merchant.

The Merchant can obtain information on the status of the charge made through the 'begin-single-charge' API in the following ways

* 'query-charge' API
* notification to a Merchant's notification URL specified in the 'begin-single-charge' request

+ Request (<<Add Header Value>>)

    + Attributes (BeginSingleChargeRequest)


    + Body

            <begin-single-charge-request>
              <country>US</country>
              <merchant-id>gatewaymerchant</merchant-id>
              <merchant-request-id>1602044513536</merchant-request-id>
              <merchant-transaction-id>1602044514238</merchant-transaction-id>
              <merchant-item-description>Fun Item</merchant-item-description>
              <currency>USD</currency>
              <total-amount>20</total-amount>
              <timeout after="10000" />
              <payment-method>superwallet</payment-method>
              <charge-type>hosted</charge-type>
              <notification-url>https://www.boku.com/notify</notification-url>
              <hosted>
                <forward-url>https://www.boku.com/forward</forward-url>
              </hosted>
            </begin-single-charge-request>


+ Response 200 (application/xml)
    + Attributes (BeginSingleChargeResponse)


    + Body

            <begin-single-charge-response>
              <result>
                <reason-code>0</reason-code>
                <message>Operation Successful</message>
                <retriable>false</retriable>
                <status>OK</status>
              </result>
              <timestamp>2020-10-06 21:22:01</timestamp>
              <merchant-id>gatewaymerchant</merchant-id>
              <merchant-request-id>1602044513536</merchant-request-id>
              <merchant-transaction-id>1602044514238</merchant-transaction-id>
              <charge-id>6n2nmozqd4s0y485gh711o2z</charge-id>
              <charge-status>in-progress</charge-status>
              <country>US</country>
              <payment-method>superwallet</payment-method>
              <hosted>
                <redirect-url>https://www.superwallet.com/authorize</redirect-url>
              </hosted>
            </begin-single-charge-response>




# Data Structures

## BeginSingleChargeRequest (object)
'begin-single-charge' Request - General Parameters

### Properties
+ `country` (string, required) - Country code in ISO 3166-1-alpha-2 standard
+ `merchantId` (string, required) - Boku assigned merchant ID
+ `merchantRequestId` (string, required)

    Unique merchant assigned request ID
    
    Multiple requests received with the same request ID in this field will be handled idempotently within the idempotency window.

+ `merchantTransactionId` (string, optional) - Merchant assigned transaction ID
+ `merchantData` (string, optional) - Merchant supplied meta data. This meta data is returned in the 'begin-single-charge' response and can be available in merchant reports.
+ `merchantItemDescription` (string, required) - A purchase description of the item.
+ `merchantConsumerId` (string, optional) - Consumer id assigned by the merchant
+ `currency` (string, required) - ISO 4217 3 letter currency code.
+ `totalAmount` (number, required) - Total amount to charge, including tax
+ `timeout` (Timeout, optional) - Specifies how long to block waiting for a response
+ `consumerIpAddress` (string, optional) - The IP address of the consumer. Must be IPv4 address.
+ `paymentMethod` (string, required)

    The payment method the consumer has selected.
    
    Each wallet provider will be its own payment method. A list of available values will be provided on demand.

+ `chargeType`: `hosted` (string, required) - Type of charge
+ `notificationUrl` (string, optional) - Supplies the URL for Boku to send a notification once the charge is complete
+ `hosted` (BeginSingleChargeRequestHosted, required) 
+ `sellerOfRecord` (SellerOfRecord, optional) - Optin and Charge Request API can be made for specific Seller of Record previously registered with Boku.


## BeginSingleChargeRequestHosted (object)


### Properties
+ `forwardUrl` (string, required) - Supplies the URL for Boku to redirect the consumer back to the merchant UI to complete authentication.
+ `useMobileFlow`: `false` (boolean, optional)

    True if a mobile-optimized purchase flow should be used for this request, false otherwise.
    
    Example: A non-mobile-optimized flow could display a QR code on the user's mobile. The user would be unable to scan the QR code because they are already on their mobile.
    
    A mobile-optimized flow could display a mobile login page to the user.



## BeginSingleChargeResponse (object)


### Properties
+ `result` (Result, required) - The 'result' element is defined in every response type. It is used to convey the outcome of an API request.
+ `timestamp` (string, optional)

    Time request was received ("YYYY-MM-DD hh:mm:ss").
    
    All timestamps are in UTC.

+ `merchantId` (string, required) - Boku assigned merchant ID
+ `merchantRequestId` (string, required) - Merchant assigned unique request ID
+ `merchantTransactionId` (string, optional) - Merchant assigned transaction ID
+ `merchantData` (string, optional) - Merchant supplied metadata
+ `chargeId` (string, optional)

    Unique ID for each charge generated by Boku.
    If null, means no charge was created, e.g. because the request was rejected.

+ `chargeStatus` (enum[string], optional)

    Status of the charge at the time this response was returned.
    
    If 'in-progress' is returned, the charge call should be re-issued with the same request ID until a final status is reached.
    If null, means no charge was created, e.g. because the request was rejected.

    + `success`
    + `failed`
    + `in-progress`
+ `country` (string, optional) - Country code in ISO 3166-1-alpha-2 standard
+ `paymentMethod` (string, required) - The payment method selected
+ `hosted` (BeginSingleChargeResponseHosted, optional) 
+ `sellerOfRecord` (SellerOfRecord, optional) - Optin and Charge Request API can be made for specific Seller of Record previously registered with Boku.


## BeginSingleChargeResponseHosted (object)


### Properties
+ `redirectUrl` (string, required) - URL, where the user should be redirected to so the charge, can be authorized


## Charge (object)


### Properties
+ `result` (Result, required) - The 'result' element is defined in every response type. It is used to convey the outcome of an API request.
+ `chargeStatus` (enum[string], required)

    Status of the charge at the time this response was returned.
    
    If 'in-progress' is returned, the charge call should be re-issued with the same request ID until a final status is reached.
    If null, means no charge was created, e.g. because the request was rejected.

    + `success`
    + `failed`
    + `in-progress`
+ `chargeId` (string, required) - Unique ID for the charge generated by Boku.
+ `timestamp` (string, required)

    Time original charge request was received ("YYYY-MM-DD hh:mm:ss").
    
    All timestamps are in UTC.

+ `merchantId` (string, required) - Boku assigned merchant ID
+ `merchantTransactionId` (string, optional) - Merchant assigned transaction ID
+ `country` (string, required) - Country code in ISO 3166-1-alpha-2 standard
+ `networkId` (string, required) - Issuer's Network ID
+ `currency` (string, required) - ISO 4217 3 letter currency code.
+ `totalAmount` (number, required) - Total amount charged or attempted to charge, including tax
+ `merchantItemDescription` (string, required) - A short purchase description that appears on the consumer bill.
+ `reversal` (Reversal, optional)

    Contains information about the reversal status of this transaction.
    If present, charge may be considered reversed. If not present, no reversal request has been received.

+ `merchantData` (string, optional) - Merchant supplied meta data


## ChargeRequest (object)
'charge' Request - General Parameters

### Properties
+ `merchantId` (string, required) - Boku assigned merchant ID
+ `merchantRequestId` (string, required)

    Unique merchant assigned request ID
    
    Multiple requests received with the same request ID in this field will be handled idempotently within the idempotency window.

+ `merchantTransactionId` (string, optional) - Merchant assigned transaction ID
+ `merchantData` (string, optional) - Merchant supplied meta data. This meta data is returned in the 'charge' response and can be available in merchant reports.
+ `merchantItemDescription` (string, required) - A short purchase description that appears on the consumer bill. A string longer than 20 characters will be truncated.
+ `optinId` (string, required) - Boku assigned consumer opt-in ID
+ `currency` (string, required) - ISO 4217 3 letter currency code.
+ `totalAmount` (number, required) - Total amount to charge, including tax
+ `timeout` (Timeout, optional) - Specifies how long to block waiting for a response
+ `consumerIpAddress` (string, optional) - IP address of consumer. Must be IPv4 address.
+ `subscription` (Subscription, optional) 
+ `sellerOfRecord` (SellerOfRecord, optional) - Optin and Charge Request API can be made for specific Seller of Record previously registered with Boku.


## ChargeResponse (object)
'charge' Response - General Elements

### Properties
+ `result` (Result, required) - The 'result' element is defined in every response type. It is used to convey the outcome of an API request.
+ `timestamp` (string, optional)

    Time request was received ("YYYY-MM-DD hh:mm:ss").
    
    All timestamps are in UTC

+ `merchantId` (string, required) - Boku assigned merchant ID
+ `merchantRequestId` (string, required) - Merchant assigned unique request ID
+ `merchantTransactionId` (string, optional) - Merchant assigned transaction ID
+ `merchantData` (string, optional) - Merchant supplied meta data
+ `optinId` (string, required) - Boku assigned consumer opt-in ID
+ `chargeId` (string, optional)

    Unique ID for each charge generated by Boku.
    If null, means no charge was created, e.g. because the request was rejected.

+ `chargeStatus` (enum[string], optional)

    Status of the charge at the time this response was returned.
    
    If 'in-progress' is returned, the charge call should be re-issued with the same request ID until a final status is reached.
    If null, means no charge was created, e.g. because the request was rejected.

    + `success`
    + `failed`
    + `in-progress`
+ `country` (string, optional) - Country code in ISO 3166-1-alpha-2 standard
+ `networkId` (string, optional) - Issuer's Network ID
+ `sellerOfRecord` (SellerOfRecord, optional) - Optin and Charge Request API can be made for specific Seller of Record previously registered with Boku.
+ `settlement` (Settlement, optional) 


## InvalidRequestField (object)
Provides per-field error information in the case where the submitted request did not satisfy validation constraints.

### Properties
+ `path` (string, optional)

    Property path of the field that was in error. The element or attribute name is given in camel-case, with nested objects delimited by `.` (period)
    
    If there are multiple distinct errors regarding a particular field, it may appear more than once. I.e. `field[path]` is not necessarily unique.

+ `reason` (string, optional) - A descriptive reason why the field was invalid. This message is not localized and so is not appropriate for user messaging.


## Period (object)
The period of the subscription (at which interval the consumer is being charged)

### Properties
+ `unit` (enum[string], required)

    A period is comprised of a unit of time (day, week, month, year) and a count (how many units per period).
    
    For example, to define a "3 month" period one would set the unit as "month" and the count as "3".

    + `day`
    + `week`
    + `month`
    + `year`
+ `count` (number, required) - The count of units in the period


## QueryChargeRequest (object)
'query-charge' Request

### Properties
+ `country` (string, required) - Country code within which to search for charges
+ `merchantId` (string, required) - Boku assigned merchant ID
+ `chargeId` (string, optional)

    The charge-id returned from the original charge-response.
    Will match only a single transaction.

+ `merchantRequestId` (string, optional)

    The merchant-request-id of the original charge-request.
    Will match only a single transaction.
    
    **Note:** merchant-request-id is only valid within 24 hours of the original charge request. After this time, it will return no results.

+ `merchantTransactionId` (string, optional)

    Merchant assigned transaction ID supplied in the original charge-request.
    May match multiple transactions in the case where the merchant reuses merchant-transaction-ids across different request IDs, as Boku does not enforce uniqueness on this value.



## QueryChargeResponse (object)


### Properties
+ `result` (Result, required) - The 'result' element is defined in every response type. It is used to convey the outcome of an API request.
+ `charges` (array[Charge], optional) 


## Result (object)
The 'result' element is defined in every response type. It is used to convey the outcome of an API request.

### Properties
+ `status` (enum[string], required) - The status of the operation
    + `OK`
    + `ERROR`
+ `reasonCode` (number, required) - Provides additional information for the status
+ `message` (string, required) - Description of the reason code
+ `retriable` (boolean, required) - **true** if the request can be retried; **false** otherwise
+ `retryDelay` (number, optional) - Minimum milliseconds to delay before re-trying request
+ `invalidRequestFields` (array[InvalidRequestField], optional) 


## Reversal (object)
Contains information about the reversal status of this transaction.
If present, charge may be considered reversed. If not present, no reversal request has been received.

### Properties
+ `timestamp` (string, required)

    Time original reverse-charge request was received ("YYYY-MM-DD hh:mm:ss").
    
    All timestamps are in UTC.

+ `reversalId` (string, required) - Boku assigned reversal ID allocated at the time of the original reversal request


## ReverseChargeRequest (object)
'reverse-charge' Request - General Parameters

### Properties
+ `merchantId` (string, required) - Boku assigned merchant ID
+ `merchantRequestId` (string, required) - Merchant assigned request ID of the original charge-request being reversed
+ `country` (string, required) - Country code of the original charge to be reversed (same value as the original charge-request)


## ReverseChargeResponse (object)
'reverse-charge' Response - General Elements

### Properties
+ `result` (Result, required) - The 'result' element is defined in every response type. It is used to convey the outcome of an API request.
+ `timestamp` (string, optional)

    Time request was received ("YYYY-MM-DD hh:mm:ss").
    
    All timestamps are in UTC.

+ `merchantId` (string, required) - Boku assigned merchant ID
+ `merchantRequestId` (string, required) - Merchant assigned request ID
+ `reversalId` (string, optional) - Boku assigned reversal ID
+ `country` (string, required) - Country code in ISO 3166-1-alpha-2 standard
+ `chargeId` (string, optional) - Unique ID for each charge generated by Boku


## SellerOfRecord (object)
Optin and Charge Request API can be made for specific Seller of Record previously registered with Boku.

### Properties
+ `id` (string, required) - ID of seller of record previously registered with Boku. Boku generated Seller of Record id will be 24 character alpha-numeric string.


## Settlement (object)


### Properties
+ `currency` (string, required) 
+ `grossMerchantAmount` (number, required) 
+ `exchangeRate` (number, required) 


## Subscription (object)


### Properties
+ `isSubscription` (boolean, required) - True if the charge is for a subscription, false otherwise
+ `period` (Period, optional) - The period of the subscription (at which interval the consumer is being charged)
+ `renewal` (boolean, optional) - False if this is the first charge in a subscription, true if the charge is a renewal (second period onwards)


## Timeout (object)
Specifies how long to block waiting for a response

### Properties
+ `after` (number, required) - Maximum time to block before returning a response, in milliseconds. The value `0` means do not block, and there is no way to specify infinity.

